[package]
name = "ftx-rs"
version = "0.1.0"
authors = ["Mikhail Babenko <misha-babenko@yandex.ru>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
url = "2.1"
hmac = "0.10"
sha2 = "0.9"
tokio = "1.0.0"
tokio-tungstenite = { version = "0.13", features = ["connect", "tls"] }
